version: 0.2
env:
  exported-variables:
      - ALL_PHASES_STATUS

phases:
  install:
    commands:
        echo "[Install] : $EXPORT_PROJECT_NAME"
  pre_build:
    commands:
      - terraform init
  build:
    commands:
      - terraform apply
  post_build:
    commands:
        - echo "[Post Build] : $${ALL_PHASES_STATUS}"
artifacts:
  files:
    - '**/*'
