version: 0.2
env:
  exported-variables:
      - ALL_PHASES_STATUS
phases:
  install:
    commands:
        echo "[Install] : $EXPORT_PROJECT_NAME"
  pre_build:
    commands:
      - terraform init 
      - terraform plan
  build:
    commands:
      - terraform apply -var-file="${terraform.workspace}.tfvars"
  post_build:
    commands:
        - echo "[Post Build] : $${ALL_PHASES_STATUS}"

